# Generated by Django 5.2.4 on 2025-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='teacher_uploads/')),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('address', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
