# Generated by Django 5.2.4 on 2025-07-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_pic',
            new_name='photo',
        ),
    ]
