# Generated by Django 5.2.4 on 2025-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_rename_profile_pic_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='contact',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
